config/routes.rb
ExamApp::Application.routes.draw do

  resources :logs do
    collection do
      post "download_logs"
    end
  end
  resources :report_errors

  resources :proofs do
    member do
      get "approve_vip","reject_vip"
    end
  end

  match '/signout'=> 'sessions#destroy'
  resources :feedbacks do
    member do
      post :edit
    end
  end
  resources :combine_practices 
  resources :item_pools do
    collection do
      post :search_condition,:choose_type,:colligation_choose_type,:update_problem,:item_pools_mavin_problem
      post :create_paper,:items_search,:ajax_item_pools_problem_info,:ajax_item_pools_edit_problem,
        :ajax_item_pools_edit_question,:ajax_item_pools_mavin_problem
      get :paper_item, :new_page,:index_search
    end
    member do
      get :revise_item
      post :items_search,:add_problems
    end
  end

  namespace :user do
    resources :examinations do
      member do
        post "save_result", "five_min_save", "check_exam_pwd"
        get "do_exam", "enter_password"
      end
      collection do
        get "error_page"
      end
    end
    resources :exam_users do
      collection do
        get "session_new", "affiremed_false","affiremed_success"
        post "exam_session","search"
        get "search_list"
      end
      member do
        get "my_results"
        get "exam_user_affiremed"
        post "edit_score","edit_name"
      end
    end
    resources :combine_practices do
      member do
        get "start","show2","show3","show4","show5","show6"
      end
    end
    resources :collections do
      collection do
        post "search"
      end
    end
  end
  
  resources :users do
    collection do
      get "roles_manage", "export_info"
      get "get_proof_code", "get_register_code", "re_active", "active_success", "active_false"
      post "add_role","load_set_right","set_right","load_edit_role","edit_role","load_set_role",
        "set_role","index_search","do_export_info"
    end
    member do
      get "active", "user_active"
      post "update_info"
    end
  end
  namespace :rater do
    resources :exam_raters do
      collection do
        get "session","check_paper"
      end
      member do
        post "edit_value"
        get "rater_session","get_score"
        post "rater_login","over_answer"
        get "reader_papers","answer_paper"
      end
    end
  end
  resources :results do
    collection do
      post "search"
      get "search_list"
    end
  end
  resources :sessions do
    collection do
      get "get_code"
      post "user_code"
    end
    member do
      get "new_code","active"
      post "update_user_code"
    end
  end

  resources :questions do
    member do
      post "edit_question"
    end
    collection do
      post "ajax_small_question_type","create_small_question"
    end
  end
  resources :paper_blocks do
    member do
      post "choose_type"
    end
    collection do
      post "load_edit_problem"
      post "load_create_problem"
    end
  end
  resources :problems do
    collection do
      get "delete_colligation_question","change_colligation_position"
      post "mavin_problem",:des,"description_destroy"
    end
    member do
      post "update_problem","create_part_description","load_edit_part","update_part_description"
    end
  end

  resources :exam_users do
    collection do
      get "create_exam_user"
      post "add_item", "leadin"
    end
    member do
      get "new_exam_two"
      post "login"
      post "update_exam_user" 
    end
  end

  resources :exam_raters do
    collection do
      get "new_exam_three", "create_exam_rater"
    end
    member do
      get "accept_score","cancel_score","random_paper"
      post "update_exam_rater","login_rater"
    end
  end

  resources :examinations do
    collection do
      get "search_list", "new_exam_one"
      post "search"
    end
    member do
      get "export_user_unaffirm", "edit_base_info", "back_base_info",
        "published", "paper_delete", "search_papers", "choose_papers", "exam_result", "single_result_list", "close"
      post "create_step_one", "update_base_info", "search_result"
    end
  end
 
  resources :papers do
    collection do
      get "new_step_one", "search_list"
      post "create_step_one", "create_step_two", "search", "create_exam_one", "create_exam_two", "create_exam_three", "exam_list"
      post "problem_destroy", "edit_block"
    end
    member do
      get "new_step_two", "answer_paper", "create_all_paper"
      post "change_info", "hand_in"
    end
  end

  resources :uploads do
    collection do
      post "upload_images", "upload"
    end
  end

  resources :pages do
    collection do
      get "create_step_one", "create_step_two", "edit", "create_exam_one", "create_exam_two", "create_exam_three",
        "exam_list", "show_exam", "edit_exam_base", "edit_exam_users", "edit_exam_raters", "setting",
        "result_list", "my_exam_list", "exam_results", "result_list", "show_result", "my_results", "answer_paper"
      get "rater_login", "paper_list", "rate_paper"
      get "exam_query_login", "my_results_simple", "user_exams"
    end
  end

 

  root :to => "sessions#new"

end
 

app/models/tag.rb
# encoding: utf-8
class Tag < ActiveRecord::Base
  has_many :problem_tag_relations,:dependent=>:destroy
  has_many :problems,:through=>:problem_tag_relations,:foreign_key=>"problem_id"
  has_many :question_tag_relations,:dependent=>:destroy
  has_many :questions,:through=>:question_tag_relations,:foreign_key=>"question_id"

  #判断标签是否存在
  def Tag.is_exists?(*name)
    tags = Tag.find_all_by_name(*name)
    return tags.any?
    #return true or false
  end


  #创建标签
  def Tag.create_tag(name)
    new_tags = []
    real_name = {}
    existed_name = []
    name.each { |na| real_name[na] = na }
    tags = Tag.find_all_by_name(real_name.values)
    tags.collect do |t|
      new_tags << t
      existed_name << t.name
    end
    (name - existed_name).each do  |n|
      new_tags << Tag.create(:name => n, :num => (Tag.tag_num)[-1])
    end unless (name - existed_name).blank?
    return new_tags
  end

  #为tag生成有序数列 2 4 8 16 32...
  def self.create_tag_num
    tag_num = 2
    max_num = Tag.maximum("num")
    puts max_num
    tag_num = max_num * 2 if !max_num.nil? and max_num > 0
    return tag_num
  end

  #生成素数标识每个标签
  def self.tag_num
    tag_num = Tag.maximum("num")
    arr = [2]
    if tag_num.nil? or tag_num == 0
      start_num = 2
    else
      start_num = tag_num
      end_num = (start_num.to_s.length + 1) * 100
      3.step(end_num, 2) do |n|
        if Tag.is_prime?(arr, n)
          arr << n
          break if n > start_num
        end
      end      
    end
    return arr
  end


  def self.is_prime?(arr, number)
    j=0
    while arr[j] * arr[j] <= number
      return false if number % arr[j] ==0
      j +=1
    end
    return true
  end

end

app/controllers/exam_raters_controller.rb
# encoding: utf-8
class ExamRatersController < ApplicationController
  before_filter :access?
  
  def create_exam_rater #创建阅卷老师
    @examination = Examination.find(params[:examination_id].to_i)
    rater=ExamRater.find_by_email_and_examination_id(params[:exam_rater_infoemail],params[:examination_id])
    if rater
      flash[:error]="信息已加入"
    else
      @exam_rater=ExamRater.create!(:examination_id => @examination.id , :name => params[:exam_rater_infoname],
        :mobilephone => params[:exam_rater_infomobile], :email => params[:exam_rater_infoemail], :author_code => proof_code(6))
      UserMailer.rater_affirm(@exam_rater,@examination).deliver
    end
    @exam_raters = Examination.paginate_by_sql("select * from exam_raters r where r.examination_id = #{@examination.id}",
      :per_page => 10, :page => params[:page])
    @exam_all={}
    @relations=RaterUserRelation.find_by_sql("select sum(rate_time) long_time, count(id) sum,exam_rater_id rater_id from rater_user_relations group by exam_rater_id")
    @relations.collect() { |exam_rater| @exam_all["#{exam_rater.rater_id}"]=exam_rater }
    render :partial => "/examinations/exam_rater"
  end

  def destroy  #删除阅卷老师
    @exmination_id=ExamRater.find(params[:id].to_i).examination_id
    ExamRater.delete(params[:id].to_i)
    @exam_raters = Examination.paginate_by_sql("select * from exam_raters r where r.examination_id = #{@exmination_id}",
      :per_page => 10, :page => params[:page])
    @exam_all={}
    @relations=RaterUserRelation.find_by_sql("select sum(rate_time) long_time, count(id) sum,exam_rater_id rater_id from rater_user_relations group by exam_rater_id")
    @relations.collect() { |exam_rater| @exam_all["#{exam_rater.rater_id}"]=exam_rater }
    @examination=Examination.find(@exmination_id)
    render :partial=>"/examinations/exam_rater"
  end

  def edit  #阅卷老师信息编辑
    @exam_rater =ExamRater.find(params[:id].to_i)
    render :partial=>"/examinations/edit_exam_rater"
  end

  def update_exam_rater #更新阅卷老师信息
    @exam_rater =ExamRater.find(params[:id].to_i)
    rater=ExamRater.find_by_email_and_examination_id(params[:email],@exam_rater.examination_id)
    if rater
      if @exam_rater.email == params[:email]
        @exam_rater.update_attributes(:name=>params[:name],:email=>params[:email],:mobilephone=>params[:mobilephone])
      else
        flash.now[:error]="be_used"
      end
    else
      @exam_rater.update_attributes(:name=>params[:name],:email=>params[:email],:mobilephone=>params[:mobilephone])
    end
    @exam_all={}
    @relations=RaterUserRelation.find_by_sql("select sum(rate_time) long_time, count(id) sum,exam_rater_id rater_id from rater_user_relations group by exam_rater_id")
    @exam_all["#{@exam_rater.id}"]=@relations
    render :partial=>"/examinations/back_exam_rater"
  end
  
  def login_rater
    @examination = Examination.find(params[:id].to_i)
    @info_raters = get_text(params[:rater_info].strip)
    str="阅卷老师重复的信息："
    str += ExamRater.check_rater(@info_raters,params[:id].to_i)
    if str=="阅卷老师重复的信息："
      ExamRater.create_raters(@info_raters,@examination)
      @exam_raters = Examination.paginate_by_sql("select * from exam_raters r where r.examination_id = #{@examination.id}",
        :per_page => 10, :page => params[:page])
      flash[:notice] = "导入信息成功。"
      render :update do |page|
        page.replace_html "exam_rater_list" , :partial => "/examinations/exam_rater"
        page.replace_html "add_info" ,  :inline => "<script>show_name('exam_rater_list','pile_exam_rater');</script>"
      end
    else
      render :update do |page|
        page.replace_html "add_info" ,  :text => "<font color='blue'>#{str}</font>"
      end
    end
  end

  def accept_score
    @rater_relations=RaterUserRelation.find_by_sql("select * from rater_user_relations r where r.exam_rater_id=#{params[:id]} and r.is_authed = 0")
    unless @rater_relations.blank?
      @rater_relations.each do |rater_relation|
        rater_relation.toggle!(:is_authed)
      end
      flash[:success]="当前老师批改的成绩认可成功。"
    else
      flash[:warn]="当前老师没有新批改试卷。"
    end
    redirect_to request.referer
  end
  
  def cancel_score
    @rater_relations=RaterUserRelation.find_all_by_exam_rater_id(params[:id])
    unless @rater_relations.blank?
      @rater_relations.each do |rater_relation|
        unless rater_relation.is_authed ==true
          ExamUser.find(rater_relation.exam_user_id).update_attributes(:total_score=>0)
          rater_relation.destroy
        end
      end
      flash[:notice]="当前老师批改的成绩已经作废。"
    else
      flash[:warn]="当前老师没有新批改试卷。"
    end
    redirect_to request.referer
  end

  def random_paper
    @rater=ExamRater.find(params[:id])
    @examination=Examination.find(@rater.examination_id)
    @exam_users=ExamUser.find_by_sql("select eu.* from exam_users eu inner join rater_user_relations r on r.exam_user_id = eu.id
      where eu.examination_id = #{@examination.id} and r.is_authed=0 and r.is_checked=0 order by rand() limit 1")
    unless @exam_users.blank?
      @exam_user=@exam_users[0]
      RaterUserRelation.find_by_exam_user_id(@exam_user.id).update_attributes(:is_checked=>true)
      doc=ExamRater.open_file(@exam_user.answer_sheet_url)
      xml=ExamRater.open_file("/papers/#{doc.elements[1].attributes["id"]}.xml")
      @xml=ExamUser.answer_questions(xml,doc)
    else
      flash[:warn] = "当前老师没有新批改试卷。"
      redirect_to examination_path(@examination)
    end
  end
end

app/controllers/rater/exam_raters_controller.rb
# encoding: utf-8
class Rater::ExamRatersController < ApplicationController
  layout "rater"

  def rater_session #阅卷老师登陆页面
    @rater=ExamRater.find(params[:id])
    @examination=Examination.find(params[:examination])
    render "/rater/exam_raters/session"
  end

  def rater_login  #阅卷老师登陆
    @rater=ExamRater.find(params[:id])
    @examination=Examination.find(params[:examination_id])
    if @rater.author_code==params[:author_code]
      cookies[:rater_id]={:value =>@rater.id, :path => "/", :secure  => false}
      flash[:success]="登陆成功"
      redirect_to  "/rater/exam_raters/#{@examination.id}/reader_papers"
    else
      flash[:error]="阅卷码不正确，请核对！"
      render "/rater/exam_raters/session"
    end
  end

  def reader_papers  #答卷批阅状态显示
    @examination=Examination.find(params[:id])
    @exam_paper_total =ExamUser.get_paper(params[:id])
    @user=User.find(@examination.creater_id)
    @exam_score_total = 0
    @exam_paper_marked = 0
    @exam_paper_total.each do |e|
      @exam_score_total +=1 unless e.relation_id
      @exam_paper_marked +=1 if e.is_marked==1
    end unless @exam_paper_total.blank?
  end

  def check_paper  #选择要批阅的答卷
    @exam_user= ExamUser.find_by_sql("select eu.id from exam_users eu
      left join rater_user_relations r on r.exam_user_id = eu.id
      where eu.answer_sheet_url is not null and eu.examination_id = #{params[:examination_id].to_i}
      and r.exam_user_id is null order by rand() limit 1")
    unless @exam_user.blank?
      redirect_to "/rater/exam_raters/#{@exam_user[0].id}/answer_paper"
    else
      flash[:notice] = "当场考试试卷已经全部阅完。"
      redirect_to request.referer
    end
  end

  def answer_paper #批阅答卷
    @exam_user = ExamUser.find(params[:id])
    doc=ExamRater.open_file(@exam_user.answer_sheet_url)
    xml=ExamRater.open_file("/papers/#{doc.elements[1].attributes["id"]}.xml")
    @xml = ExamUser.answer_questions(xml,doc)
    if @xml.attributes["ids"] == "-1"
      flash[:notice] = "感谢您的参与，当前试卷没有需要批改的试卷。"
      redirect_to request.referer
    else
      RaterUserRelation.create(:exam_rater_id => cookies[:rater_id],
        :exam_user_id => @exam_user.id, :started_at => Time.now)
    end
  end

  def over_answer #批阅完成，给答卷添加成绩
    @exam_relation = RaterUserRelation.find_by_exam_user_id(params[:id])
    @exam_relation.toggle!(:is_marked)
    @exam_relation.update_attributes(:rate_time=>((Time.now-@exam_relation.started_at)/60+1).to_i)
    @exam_user = ExamUser.find(params[:id])
    url="/result/#{params[:id]}.xml"
    doc = ExamRater.open_file(url)
    score = 0
    doc.elements[1].elements[1].each_element do |element|
      element.add_attribute("score","#{params["single_value_#{element.attributes["id"]}"]}")
      element.add_attribute("reason","#{params["reason_for_#{element.attributes["id"]}"]}")
      score += element.attributes["score"].to_i
    end
    doc.elements["paper"].elements["rate_score"].text = score
    #@doc=ExamRater.rater(doc,params[:id], score)
    self.write_xml("#{Constant::PUBLIC_PATH}"+url, doc)
    redirect_to "/rater/exam_raters/#{ @exam_user.examination_id}/reader_papers"
  end

  def destroy #退出
    cookies.delete(:rater_id)
    cookies.delete(:examination_id)
    render :inline=>"<script>window.close();</script>"
  end

  def show
    @exam_rater=ExamRater.find(params[:id])
  end
  def edit_value #编辑考分
    @exam_rater=ExamRater.find(params[:id])
    @exam_rater.update_attributes(:name=>params[:value])
    render :inline=>"name"
    render :inline=>"姓&nbsp;&nbsp;&nbsp;&nbsp;名:#{ @exam_rater.name}"
  end

  def index #参加的阅卷列表
    @exam_rater=ExamRater.find(cookies[:rater_id])
    @exam_list=ExamRater.find_all_by_email(@exam_rater.email)
  end
end

app/helpers/rater/exam_raters_helper.rb
module Rater::ExamRatersHelper
end

app/views/rater/exam_raters/_single_question.erb
<div class="products_list_style_box" id="question_info_<%= single_question.attributes["id"].to_i %>" style="display:none"  >
  <div class="arrow" style="top:35px;"></div>
  <div class="big_pic_box" style="top:0px;">
    <div class="in">
      <div class="title"><%= single_question.elements["title"].text %></div>
      <% problem_ids="-1" %>
      <% single_question.elements["questions"].each_element do |question| %>
        <%= render :partial => "/common/show_single_question", :object => question %>
        <div class="title">
          <div>考生答案：<%= question.attributes["user_answer"] %></div>
        </div>
        <div class="title">
          <input type="hidden" value="<%= question.attributes["score"] %>" id="fact_value_<%=  question.attributes['id'] %>" name="fact_value_<%=question.attributes['id'] %>"/>
          <input value="<%= @exam_user.id %>" id="answer_id" name="answer_id" type="hidden" />
          <input  type="hidden" value="0" id="if_submited_<%= question.attributes['id'] %>" name="if_submited_<%= question.attributes['id'] %>"/>
          <font color="red">*</font>请给出得分：<input type="text" size="5" name="single_value_<%=question.attributes['id'] %>"
                       id="single_value_<%=question.attributes['id'] %>" value="" />分
        </div>
      <div class="title">
        <font color="red">*</font>请填写评分理由：<br/>
        <textarea type="text" name="reason_for_<%=question.attributes['id'] %>" cols="40"
                  id="reason_for_<%=question.attributes['id'] %>"></textarea>
      </div>
        <% problem_ids = problem_ids+("_"+question.attributes["id"]) %>
        <div id="flash_part_<%= question.attributes["id"].to_i %>"></div>
      <% end %>
      <input type="hidden" value="<%=problem_ids.to_s  %>"/>
      <h2><input type="button" value="确定" onclick="javascript:compare_value('<%= problem_ids.to_s %>',1)" /></h2>
      <div id="flash_part_<%= single_question.attributes["id"].to_i %>"></div>
    </div>
  </div>
</div>

app/views/rater/exam_raters/answer_paper.erb
<div id="paper_show_info">
  <ul class="tab_biz">
    <li class="actived"><a href="javascript:void(0);"><%= @xml.elements['base_info'].elements['title'].text %></a></li>
  </ul>
</div>
<%= form_for :over,:url=>"/rater/exam_raters/#{@exam_user.id}/over_answer"  do |f| %>
  <div class="biz_art_list_box">
    <center>
      <input type="hidden" id="problem_id" name="problem_id" value="<%=@xml.attributes["ids"]  %>" />
      <input type="hidden" name="examination_id" id="examination_id" value="<%=@exam_user.examination_id  %>" />
      <%=f.submit value="批阅完毕" ,:disabled=>"disabled",:id=>"button_id"  %>
      <div id="flash_notice"></div>
    </center>
  </div>
  <% @xml.elements['blocks'].each_element do |block|%>
    <h1 class="biz_art_title" id="block_show"><%= block.elements['base_info'].elements['title'].text %> (共<%= block.attributes['total_num'] %>题，总分:<%= block.attributes['total_score'] %>分)
    </h1>
    <div class="biz_art_list_box">
      <%= block.elements["base_info"].elements["description"].text.to_s.html_safe %>
      <ul>
        <% if !block.elements['problems'].nil? %>
          <% block.elements['problems'].each_element do |problem| %>
            <% if !problem.elements['title'].nil? %>
              <li>
                <%= render :partial=>"/rater/exam_raters/single_question",:object=>problem %>
                <h2><a href="javascript:void(0)" onclick="javascript:compare_value(<%= problem.attributes["id"].to_i %>,0)">
                    <%= truncate_u(problem.elements['title'].text.to_s.html_safe.gsub(/<[^{><}]*>/, ""), 40) %>
                  </a>
                </h2>
              </li>
              <div class="links">
                <%= form_for :delete,:html => {:name=>"delete_form_#{problem.attributes['id']}", :id =>"delete_form_#{problem.attributes['id']}"}, :url=>"/papers/problem_destroy" do |f|%>
                  <%= f.hidden_field :xpath,:value=>problem.xpath %><%= f.hidden_field :paper_id,:value=>@xml.root.attributes["id"] %>
                <% end %>
              </div>
            <% end %>
          <% end %>
        <% end %>
      </ul>
    </div>
  <% end %>
<% end %>
<div class="clear"></div>
<script type="text/javascript">active_button()</script>

app/views/rater/exam_raters/index.erb
<table>
  <tr>
    <th width="200">考试名称</th>
    <th width="150">考试开始时间</th>
  </tr>
  <%  @exam_list.each do |exam| %>
    <% examination=Examination.find(exam.examination_id) %>
    <tr>
      <td ><%= link_to "#{examination.title}","/rater/exam_raters/#{exam.id}/rater_session?examination=#{examination.id}" %></td>
      <td ><%= examination.start_at_time.nil? ? "无限制" :examination.start_at_time.strftime("%Y-%m-%d %H:%M:%S") %></td>
    </tr>
    <% end %>
  </table>

app/views/rater/exam_raters/reader_papers.erb
<input type="hidden" value="<%=@examination.id  %>" name="examination" id="examination"/>
<%= @examination.title %>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(&nbsp;&nbsp;
<% if @examination.exam_time.nil? %>
  <a>任何时间</a>
<%  else %>
  <%= @examination.exam_time %>分钟&nbsp;&nbsp;&nbsp;
<% end %>
<% if !@examination.start_at_time.nil? %>
  考试开始时间：<%=@examination.start_at_time.strftime("%Y-%m-%d  %H:%M")  %>
  &nbsp;&nbsp;&nbsp
  入场时间：<%=@examination.start_at_time.strftime("%H:%M")%>&nbsp;到&nbsp;
  <%=@examination.start_end_time.strftime("%H:%M") %>
<% else %>
  试卷更新时间: <%= @examination.updated_at.strftime("%Y-%m-%d  %H:%M") %>
<% end %> &nbsp;&nbsp;)
<p>
  本次考试由&nbsp;&nbsp<%=@user.name  %>&nbsp;&nbsp;组织
<div  align="center">
  <table border="1" >
    <tr>
      <td>
        <% if @exam_score_total >0  %>
          <font color="blue" size="5"><%= link_to "开始批阅","/rater/exam_raters/check_paper?examination_id=#{@examination.id}" %></font>
        <% else %>
          <font color="red" size="5">所有试卷已批阅</font>
        <% end %>
      </td>
    </tr>

  </table>
</div>
</p>
<p>
<h1>阅卷情况：</h1>
<table>
  <tr>
    <td width="60"><font color="red"><%= @exam_paper_total.size   %>&nbsp;&nbsp;份</font></td><td width="50" ><font color="red">
        <%= @exam_paper_marked %>&nbsp;&nbsp;份</font></td><td width="50"><font color="red">
        <%= @exam_score_total %>&nbsp;&nbsp;份</font></td>
  </tr>
  <tr>
    <th width="60">试卷总数</th>&nbsp;&nbsp;&nbsp;<th width="50">已批阅</th>&nbsp;&nbsp;&nbsp;<th width="50">未批阅</th>
  </tr>
</table>
</p>

app/views/rater/exam_raters/session.html.erb
<center>
<% if cookies[:rater_id].to_i==@rater.id %>
 您已经登录，是否<%= link_to "批卷","/rater/exam_raters/#{@examination.id}/reader_papers" %>
<% else %>

  <p><%= flash[:success] %></p>
<h1>尊敬的<font color="blue"> <%= @rater.name %> </font>老师，您好，请您在阅卷之前输入阅卷码，以便确认您的身份。</h1>
<%= form_for :rater ,:url=>"/rater/exam_raters/#{@rater.id}/rater_login" do %>
<p>
 <span class="must_r ">*</span>阅&nbsp;&nbsp;&nbsp;卷&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;码：<input id="author_code " name="author_code" class = "required input_style" size="30" />
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</p>
<p>
  <input type="hidden" value="<%= @examination.id %>" id="examination_id" name="examination_id" />
  <input type="submit" value="提交" />
</p>
<% end %>

<% end %>
</center>

app/views/rater/exam_raters/show.erb
<p><div id="in1" style="display:none">姓&nbsp;&nbsp;&nbsp;&nbsp;名:<input type="text" value="<%= @exam_rater.name %>" ondblclick="javascript:give_me_value('in',<%= @exam_rater.id %>)"  id="in" />
</div>
<label onclick="javascript:$('in1').style.display='block';$('out').style.display='none';" id="out" style="display:block"  >姓&nbsp;&nbsp;&nbsp;&nbsp;名：<%= @exam_rater.name %></label>


 
</p>
手机号：
<%= @exam_rater.mobilephone %>