config/routes.rb
ExamApp::Application.routes.draw do

  resources :logs do
    collection do
      post "download_logs"
    end
  end
  resources :report_errors

  resources :proofs do
    member do
      get "approve_vip","reject_vip"
    end
  end

  match '/signout'=> 'sessions#destroy'
  resources :feedbacks do
    member do
      post :edit
    end
  end
  resources :combine_practices 
  resources :item_pools do
    collection do
      post :search_condition,:choose_type,:colligation_choose_type,:update_problem,:item_pools_mavin_problem
      post :create_paper,:items_search,:ajax_item_pools_problem_info,:ajax_item_pools_edit_problem,
        :ajax_item_pools_edit_question,:ajax_item_pools_mavin_problem
      get :paper_item, :new_page,:index_search
    end
    member do
      get :revise_item
      post :items_search,:add_problems
    end
  end

  namespace :user do
    resources :examinations do
      member do
        post "save_result", "five_min_save", "check_exam_pwd"
        get "do_exam", "enter_password"
      end
      collection do
        get "error_page"
      end
    end
    resources :exam_users do
      collection do
        get "session_new", "affiremed_false","affiremed_success"
        post "exam_session","search"
        get "search_list"
      end
      member do
        get "my_results"
        get "exam_user_affiremed"
        post "edit_score","edit_name"
      end
    end
    resources :combine_practices do
      member do
        get "start","show2","show3","show4","show5","show6"
      end
    end
    resources :collections do
      collection do
        post "search"
      end
    end
  end
  
  resources :users do
    collection do
      get "roles_manage", "export_info"
      get "get_proof_code", "get_register_code", "re_active", "active_success", "active_false"
      post "add_role","load_set_right","set_right","load_edit_role","edit_role","load_set_role",
        "set_role","index_search","do_export_info"
    end
    member do
      get "active", "user_active"
      post "update_info"
    end
  end
  namespace :rater do
    resources :exam_raters do
      collection do
        get "session","check_paper"
      end
      member do
        post "edit_value"
        get "rater_session","get_score"
        post "rater_login","over_answer"
        get "reader_papers","answer_paper"
      end
    end
  end
  resources :results do
    collection do
      post "search"
      get "search_list"
    end
  end
  resources :sessions do
    collection do
      get "get_code"
      post "user_code"
    end
    member do
      get "new_code","active"
      post "update_user_code"
    end
  end

  resources :questions do
    member do
      post "edit_question"
    end
    collection do
      post "ajax_small_question_type","create_small_question"
    end
  end
  resources :paper_blocks do
    member do
      post "choose_type"
    end
    collection do
      post "load_edit_problem"
      post "load_create_problem"
    end
  end
  resources :problems do
    collection do
      get "delete_colligation_question","change_colligation_position"
      post "mavin_problem",:des,"description_destroy"
    end
    member do
      post "update_problem","create_part_description","load_edit_part","update_part_description"
    end
  end

  resources :exam_users do
    collection do
      get "create_exam_user"
      post "add_item", "leadin"
    end
    member do
      get "new_exam_two"
      post "login"
      post "update_exam_user" 
    end
  end

  resources :exam_raters do
    collection do
      get "new_exam_three", "create_exam_rater"
    end
    member do
      get "accept_score","cancel_score","random_paper"
      post "update_exam_rater","login_rater"
    end
  end

  resources :examinations do
    collection do
      get "search_list", "new_exam_one"
      post "search"
    end
    member do
      get "export_user_unaffirm", "edit_base_info", "back_base_info",
        "published", "paper_delete", "search_papers", "choose_papers", "exam_result", "single_result_list", "close"
      post "create_step_one", "update_base_info", "search_result"
    end
  end
 
  resources :papers do
    collection do
      get "new_step_one", "search_list"
      post "create_step_one", "create_step_two", "search", "create_exam_one", "create_exam_two", "create_exam_three", "exam_list"
      post "problem_destroy", "edit_block"
    end
    member do
      get "new_step_two", "answer_paper", "create_all_paper"
      post "change_info", "hand_in"
    end
  end

  resources :uploads do
    collection do
      post "upload_images", "upload"
    end
  end

  resources :pages do
    collection do
      get "create_step_one", "create_step_two", "edit", "create_exam_one", "create_exam_two", "create_exam_three",
        "exam_list", "show_exam", "edit_exam_base", "edit_exam_users", "edit_exam_raters", "setting",
        "result_list", "my_exam_list", "exam_results", "result_list", "show_result", "my_results", "answer_paper"
      get "rater_login", "paper_list", "rate_paper"
      get "exam_query_login", "my_results_simple", "user_exams"
    end
  end

 

  root :to => "sessions#new"

end
 

app/models/paper.rb
# encoding: utf-8
class Paper < ActiveRecord::Base

  require 'rexml/document'
  include REXML

  has_many :paper_blocks ,:dependent=>:destroy
  has_many :examination_paper_relations,:dependent=>:destroy
  has_many :examinations, :through=>:examination_paper_realations, :source => :examination
  belongs_to :user,:foreign_key=>"creater_id"
  belongs_to :category
  has_many :exam_users

  default_scope :order => "papers.created_at desc"

  #更新试卷基本信息
  def update_base_info(url, options = {})
    file=File.open(url)
    doc=Document.new(file)
    doc.root.elements["base_info"].elements["updated_at"].text=Time.now.strftime("%Y-%m-%d %H:%M")
    doc.root.elements["base_info"].elements["title"].text=self.title
    doc.root.elements["base_info"].elements["description"].text=self.description
    options.each do |key, value|
      doc.root.elements["base_info"].elements["#{key}"].text = value
    end unless options.empty?
    file.write(doc)
    file.close
  end

  #创建试卷的文件
  def create_paper_url(str, path, file_type)
    dir = "#{Rails.root}/public" 
    unless File.directory?(dir + "/" + path)
      Dir.mkdir(dir + "/" + path)
    end
    file_name = "/" + path + "/#{self.id}." + file_type
    url = dir + file_name
    f=File.new(url,"w+")
    f.write("#{str.force_encoding('UTF-8')}")
    f.close
    if file_type == "xml"
      self.paper_url = file_name
    else
      self.paper_js_url = file_name
    end
    self.save
  end

  #创建xml文件
  def xml_content(options = {})
    content = "<?xml version='1.0' encoding='UTF-8'?>"
    content += <<-XML
      <paper id='#{self.id}' total_num='0' total_score='0'>
        <base_info>
          <title>#{self.title.force_encoding('ASCII-8BIT')}</title>
          <category>#{self.category_id}</category>
          <creater>#{self.creater_id}</creater>
          <created_at>#{self.created_at.strftime("%Y-%m-%d %H:%M").force_encoding('ASCII-8BIT')}</created_at>
          <updated_at>#{self.updated_at.strftime("%Y-%m-%d %H:%M").force_encoding('ASCII-8BIT')}</updated_at>
          <description>#{self.description.force_encoding('ASCII-8BIT')}</description>
    XML
    options.each do |key, value|
      content+="<#{key}>#{value.force_encoding('ASCII-8BIT')}</#{key}>"
    end unless options.empty?
    content += <<-XML
      </base_info>
      <blocks>
      </blocks>
       <problem_ids></problem_ids>
      </paper>
    XML
    return content
  end

  #置试卷的使用状态
  def set_paper_used!
    self.toggle!(:is_used)
  end

  def Paper.search_mothod(user_id, start_at, end_at, title, category, per_page, page, options={})
    sql = "select * from papers where creater_id=#{user_id}"
    sql += " and created_at > '#{start_at}'" unless start_at.nil?
    sql += " and created_at < '#{end_at}'" unless end_at.nil?
    sql += " and title like '%#{title}%'" unless title.nil?
    sql += " and category_id = #{category}" unless category.nil?
    options.each do |key, value|
      sql += " and #{key} #{value} "
    end unless options.empty?
    sql += " order by created_at desc"
    puts sql
    return Paper.paginate_by_sql(sql, :per_page =>per_page, :page => page)
  end

  #生成试卷的json
  def create_paper_js
    file=File.open "#{Constant::PUBLIC_PATH}/#{self.paper_url}"
    doc = Document.new(file)
    file.close
    doc.root.elements["blocks"].each_element do |block|
      block.elements["problems"].each_element do |problem|
        problem.elements["questions"].each_element do |question|
          doc.delete_element("#{question.xpath}/answer") if question.elements["answer"]
          doc.delete_element("#{question.xpath}/analysis") if question.elements["analysis"]
        end unless problem.elements["questions"].nil?
      end 
    end
    return "papers = " + Hash.from_xml(doc.to_s).to_json
  end

  #更新试卷的题目数和总分
  def update_num_score
    file=File.open "#{Constant::PUBLIC_PATH}/#{self.paper_url}"
    doc = Document.new(file)
    file.close
    self.total_score = doc.root.attributes["total_score"].to_i
    self.total_question_num = doc.root.attributes["total_num"].to_i
    self.save
  end

end

app/models/tag.rb
# encoding: utf-8
class Tag < ActiveRecord::Base
  has_many :problem_tag_relations,:dependent=>:destroy
  has_many :problems,:through=>:problem_tag_relations,:foreign_key=>"problem_id"
  has_many :question_tag_relations,:dependent=>:destroy
  has_many :questions,:through=>:question_tag_relations,:foreign_key=>"question_id"

  #判断标签是否存在
  def Tag.is_exists?(*name)
    tags = Tag.find_all_by_name(*name)
    return tags.any?
    #return true or false
  end


  #创建标签
  def Tag.create_tag(name)
    new_tags = []
    real_name = {}
    existed_name = []
    name.each { |na| real_name[na] = na }
    tags = Tag.find_all_by_name(real_name.values)
    tags.collect do |t|
      new_tags << t
      existed_name << t.name
    end
    (name - existed_name).each do  |n|
      new_tags << Tag.create(:name => n, :num => (Tag.tag_num)[-1])
    end unless (name - existed_name).blank?
    return new_tags
  end

  #为tag生成有序数列 2 4 8 16 32...
  def self.create_tag_num
    tag_num = 2
    max_num = Tag.maximum("num")
    puts max_num
    tag_num = max_num * 2 if !max_num.nil? and max_num > 0
    return tag_num
  end

  #生成素数标识每个标签
  def self.tag_num
    tag_num = Tag.maximum("num")
    arr = [2]
    if tag_num.nil? or tag_num == 0
      start_num = 2
    else
      start_num = tag_num
      end_num = (start_num.to_s.length + 1) * 100
      3.step(end_num, 2) do |n|
        if Tag.is_prime?(arr, n)
          arr << n
          break if n > start_num
        end
      end      
    end
    return arr
  end


  def self.is_prime?(arr, number)
    j=0
    while arr[j] * arr[j] <= number
      return false if number % arr[j] ==0
      j +=1
    end
    return true
  end

end

app/controllers/papers_controller.rb
# encoding: utf-8
class PapersController < ApplicationController

  require 'rexml/document'
  include REXML
  #include PapersHelper
  before_filter :access?

  def index
    @papers = Paper.search_mothod(cookies[:user_id].to_i, nil, nil, nil, nil, 10, params[:page])
  end

  def hand_in
    puts params["radio"]["163"]
    redirect_to request.referer
  end

  def destroy
    paper = Paper.find(params[:id])
    if paper.is_used
      flash[:warn] = "试卷已经被使用！"
    else
      flash[:notice] = "删除成功！"
      paper.destroy
    end
    redirect_to "/papers"
  end

  def change_info
    @paper=Paper.find(params[:id].to_i)
    @paper.update_attributes(:title=>params[:info][:title],
      :description=>params[:info][:description], :category_id => params[:category], :types => params[:types])
    @paper.update_base_info("#{Rails.root}/public"+@paper.paper_url, {"category"=>params[:category].to_i})
    redirect_to request.referrer
  end

  def show
    begin
      file = File.open("#{Constant::PAPER_PATH}/#{params[:id]}.xml")
      @xml=Document.new(file).root
      file.close
    rescue
      flash[:error] = "当前试卷不能正常打开，请检查试卷是否正常。"
      redirect_to papers_path
    end
  end

  def new_step_two
    paper = Paper.find(params[:id].to_i)
    @question_index=0
    begin
      file = File.open("#{Constant::PUBLIC_PATH}#{paper.paper_url}")
      @xml=Document.new(file).root
      file.close
    rescue
      flash[:error] = "当前试卷不能正常打开，请检查试卷是否正常。"
      redirect_to papers_path
    end
  end

  def create_step_one
    @paper=Paper.create(:creater_id=>cookies[:user_id],:title=>params[:title].strip,
      :description=>params[:description].strip, :category_id => params[:category], :types => params[:types])
    category = Category.find(params[:category].to_i)
    @paper.create_paper_url(@paper.xml_content({"category_name" => category.name}), "papers", "xml") unless category.nil?
    redirect_to "/papers/#{@paper.id}/new_step_two"
  end

  def create_step_two
    start_time =  (params[:hour] != "") ? (params[:hour] + ":" + params[:minute]) : ""
    @block = PaperBlock.create(:paper_id => params[:module][:paper_id],
      :title => params[:module][:title],:description => params[:module][:description], 
      :time => params[:fix_time_0], :start_time => start_time)
    @block.create_block_xml("#{Rails.root}/public" + @block.paper.paper_url)
    redirect_to request.referrer
  end

  
  def problem_destroy
    url= File.open "#{Constant::PAPER_PATH}/#{params[:delete][:paper_id]}.xml"
    doc = Problem.remove_problem_xml(Problem.open_xml(url), params[:delete][:xpath])
    url.close
    Problem.write_xml(url, doc)
    redirect_to request.referrer
  end
  
  def edit_block
    start_time =  (params[:hour] != "") ? (params[:hour] + ":" + params[:minute]) : ""
    @block=PaperBlock.find(params[:block][:block_id])
    @block.update_attributes(:title=>params[:block][:title], :start_time => start_time,
      :description=>params[:block][:description], :time => params["fix_time_#{params[:block][:block_id]}"])
    xpath=params[:block][:block_xpath]
    @block.update_block_xml(xpath)
    redirect_to request.referrer
  end
  
  def search
    session[:mintime] = nil
    session[:maxtime] = nil
    session[:title] = nil
    session[:category] = nil
    session[:mintime] = params[:mintime] if !params[:mintime].nil? and params[:mintime] != ""
    session[:maxtime] = params[:maxtime] if !params[:maxtime].nil? and params[:maxtime] != ""
    session[:title] = params[:title] if !params[:title].nil? and params[:title] != ""
    session[:category] = params[:category] if !params[:category].nil? and params[:category] != ""
    redirect_to search_list_papers_path
  end

  def search_list
    @papers = Paper.search_mothod(cookies[:user_id].to_i, session[:mintime], session[:maxtime],
      session[:title], session[:category], 10, params[:page])
    render 'index'
  end
  
  #创建试卷的js文件
  def create_all_paper
    @paper = Paper.find(params[:id].to_i)
    @paper.create_paper_url(@paper.create_paper_js, "paperjs", "js")
    @paper.update_num_score
    redirect_to papers_url
  end

  
  def user_exist?
    if User.find(cookies[:user_id]) != current_user
      redirect_to root_path
    end
  end




end

app/helpers/papers_helper.rb
module PapersHelper

end

app/views/papers/_choose_question_type.erb
<div>
  <div class="title">题目类型：</div>
  <div style="float: left;padding-right: 20px;">
    <input type="radio" name="type_radio_<%= choose_question_type.attributes['id'] %>"
          value="<%= Problem::QUESTION_TYPE[:SINGLE_CHOSE] %>" id="radio1" checked />单选题
  </div>
  <div style="float: left;padding-right: 20px;">
    <input type="radio" name="type_radio_<%= choose_question_type.attributes['id'] %>"
          value="<%= Problem::QUESTION_TYPE[:MORE_CHOSE] %>" id="radio2" />多选题
  </div>
  <div style="float: left;padding-right: 20px;">
    <input type="radio" name="type_radio_<%= choose_question_type.attributes['id'] %>"
          value="<%= Problem::QUESTION_TYPE[:JUDGE] %>" id="radio3" />判断题
  </div>
  <div style="float: left;padding-right: 20px;">
    <input type="radio" name="type_radio_<%= choose_question_type.attributes['id'] %>"
          value="<%= Problem::QUESTION_TYPE[:SINGLE_CALK] %>" id="radio4" />填空题
  </div>
  <div style="float: left;padding-right: 20px;">
    <input type="radio" name="type_radio_<%= choose_question_type.attributes['id'] %>"
          value="<%= Problem::QUESTION_TYPE[:COLLIGATION] %>" id="radio5" />综合题
  </div>
  <div style="float: left;padding-right: 20px;">
    <input type="radio" name="type_radio_<%= choose_question_type.attributes['id'] %>"
          value="<%= Problem::QUESTION_TYPE[:CHARACTER] %>" id="radio6" />简答题
  </div>
  <div style="float: left;padding-right: 20px;">
    <input type="radio" name="type_radio_<%= choose_question_type.attributes['id'] %>"
          value="<%= Problem::QUESTION_TYPE[:MORE_BLANKS] %>" id="radio7" />完型填空题
  </div>
  <div class="clear"></div>
  <input type="button" value="确定" class="submit_btn"
         onClick="javascript:create_question(<%= choose_question_type.attributes['id'] %>, <%= @xml.attributes['id'] %>)"/>
  <input type="button" value="取消" class="submit_btn"
         onClick="javascript:cancel_choose_que_type(<%= choose_question_type.attributes['id'] %>)"/>
</div>

app/views/papers/_edit_block.erb
<div class="title_list_style_box" style="display:none;" id="edit_block_<%= edit_block.attributes["id"] %>">
  <div class="arrow" style="top:35px;"></div>
  <div class="block_pic_box" style="top:0px;">
    <div class="in">
      <%= form_for :block ,:url=>"/papers/edit_block" ,
        :html=>{:onsubmit=>"return edit_block_info(#{edit_block.attributes["id"]})", :class => "required-validate"} do |f|%>
        <%= f.hidden_field :block_id,:value=>edit_block.attributes["id"] %>
        <%= f.hidden_field :block_xpath,:value=>edit_block.xpath %>
        <div class="paper_block">
          试卷模块标题：<%= f.text_field :title ,:class=>"input_style max-length-50",:size=>"39",
            :value=>edit_block.elements["base_info"].elements["title"].text,:id=>"edit_block_title_#{edit_block.attributes["id"]}" %>
        </div>
        <div class="add_details">
          模块是否需要单独固定时间答完：
          <input type="radio" id="fixup_time_<%= edit_block.attributes["id"] %>" name="fixup_time_<%= edit_block.attributes["id"] %>" value="1"
                 <% unless edit_block.attributes["time"].nil? or edit_block.attributes["time"] == "" %>checked="true"<% end %>
                 onclick="javascript:show_fixup_time(1, <%= edit_block.attributes["id"] %>);" />是&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
          <input type="radio" id="fixup_time_<%= edit_block.attributes["id"] %>" value="0" name="fixup_time_<%= edit_block.attributes["id"] %>"
                 <% if edit_block.attributes["time"].nil? or edit_block.attributes["time"] == "" %>checked="true"<% end %>
                 onclick="javascript:show_fixup_time(0, <%= edit_block.attributes["id"] %>);"/>否
        </div>
        <% unless edit_block.attributes["start_time"].nil? or edit_block.attributes["start_time"] == ""
          start_time = edit_block.attributes["start_time"]
        end %>
        <div class="add_details" id="fixup_time_div_<%= edit_block.attributes["id"] %>"
             style="<% unless start_time %>display:none;<% end %>">
          开始答题时间：<input type="text" name="hour" id="hour" class="input_style validate-number"
                        size="6" value="<%= start_time.split(":")[0] if start_time %>"/>小时&nbsp;&nbsp;
          <input type="text" name="minute" id="minute" class="input_style validate-number max-value-59" size="6"
                 value="<%= start_time.split(":")[1] if start_time %>"/>分&nbsp;&nbsp;<br/>
          如：0小时30分(表示考试开始后30分钟才能答当前模块的题目，<font color="red">注：设置的时间不能超过考试时长，否则无效</font>)<br/><br/>
          请填写时间：<input type="input" name="fix_time_<%= edit_block.attributes["id"] %>"
                       id="fix_time_<%= edit_block.attributes["id"] %>" class="input_style validate-number"
                       value="<%= edit_block.attributes["time"] %>"/>分钟&nbsp;&nbsp;&nbsp;&nbsp;
        </div>
        <div class="paper_block">
          试卷模块描述：<%= f.text_area :description ,:cols=>"47",:rows=>"20",:class=>"textarea_style max-length-1000" ,
            :value=>edit_block.elements["base_info"].elements["description"].text%>
        </div>
        <div><%= f.submit "更新" ,:class=>"submit_btn" %></div>
      <% end %>
    </div>
  </div>
</div>

app/views/papers/_edit_paper_info.erb
<%= form_for :info ,:url=>"/papers/#{@xml.attributes['id']}/change_info", 
  :html=>{:onsubmit=>"return edit_paper_info('info_form', 'info_submit', 'spinner_for_submit');", :name => "info_form",
  :id => "info_form", :class => "required-validate"} do |f| %>
  <ul class="tab_biz">
    <li class="actived"><a href="javascript:void(0);"><%= @xml.elements['base_info'].elements['title'].text %></a></li>
  </ul>
  <div class="soso">
    <div>试卷编号：<%= @xml.attributes['id'] %></div>
    <div>标题：<%= f.text_field :title,:value=>@xml.elements['base_info'].elements['title'].text ,
        :id=>"edit_paper_title", :class => "required input_style max-length-50" %>
    </div>
    <div>
      <%= render :partial => "/common/modify_categories", :object => @xml.elements['base_info'].elements['category'].text %>
    </div>
    <div class="add_details">
      <font color="red">*</font><%= render :partial => "/common/examination_types" %>
    </div>
    <div>
      备注：<%= f.text_area :description, :value=>@xml.elements['base_info'].elements['description'].text ,
        :size=>40, :cols=>"55", :rows=>"2", :class=>"textarea_style max-length-100" %>
    </div>
    <%= f.submit "完成", :class=>"submit_btn" %>
    <%= image_tag "ajax-loader.gif", :id => "spinner_for_submit", :style => "display:none" %>
    <input type="button" value="取消" class="submit_btn"
           onclick="javascript:show_name('paper_show_info','paper_edit_info')"/>
  </div>
<% end %>

app/views/papers/_edit_problem.erb
<div class="products_list_style_box">
  <input type="hidden" name="edit_problem_<%= edit_problem.attributes["id"] %>" id="single_question_<%= edit_problem.attributes["id"] %>" value=""/>
  <div class="arrow" style="top:10px;"></div>
  <div class="question_pic_box" style="top:0px;">
    <div class="in">
      <%= form_for :problem , :url => "/problems/#{edit_problem.attributes["id"].to_i}/update_problem",
        :id=>"edit_form_#{edit_problem.attributes["id"]}",
        :html => {:onsubmit => "return generate_edit_questions('#{edit_problem.attributes["id"]}', '#{edit_problem.attributes["types"]}')"} do |f| %>
        <%= f.hidden_field :problem_xpath,:value=>"#{edit_problem.xpath}" %>
        <%= f.hidden_field :problem_id,:value=>"#{edit_problem.attributes["id"]}" %>
        <%= f.hidden_field :block_id,:value=>"#{edit_problem.parent.parent.attributes["id"]}" %>
        <%= f.hidden_field :paper_id,:value=>"#{@xml.attributes["id"]}" %>
        <div class="title">题面：</div>
        <input type="button" name="button" value="富文本" class="submit_btn"
               onclick="javascript:add_area('edit_title_<%= edit_problem.attributes["id"].to_i %>', this);" />
               <% title = (edit_problem.elements["title"].nil? or edit_problem.elements["title"].text.nil? or
                   edit_problem.elements["title"].text =="") ? "" : edit_problem.elements["title"].text  %>
               <%= f.text_area :title ,:cols=>"58", :rows=>"20", :class=>"textarea_style",
                 :id => "edit_title_#{edit_problem.attributes["id"].to_i}", :value=>title %>
               <% question_ids = []
               @colligation_index=0
               edit_problem.elements["questions"].each_element do |question|
                 question_ids << question.attributes["id"].to_i
                 @colligation_index+=1
               %>
                 <% if edit_problem.attributes["types"].to_i == Problem::QUESTION_TYPE[:COLLIGATION] %>
            <div id="question_list_<%= question.attributes["id"] %>">
              <input type="hidden" name="make_edit_<%= question.attributes["id"] %>" id="make_edit_<%= question.attributes["id"] %>" value="0"/>
              <div style="border: 1px solid #ccc;padding-bottom: 5px;" id="remote_question_<%= question.attributes["id"] %>">
                <%= render :partial => "/common/show_single_question", :object => question %>
                <div style="display:none;" id="change_position_div_<%= question.attributes["id"] %>"> 换序：<input type="text" id="change_colligation_position_<%= question.attributes["id"] %>"></input>&nbsp;&nbsp;<input type="button" value="确认" onclick="window.location.href='/problems/change_colligation_position?question_id=<%= question.attributes["id"].to_i %>&xml_id=<%= @xml.attributes["id"] %>&question_xpath=<%= question.xpath %>&position='+document.getElementById('change_colligation_position_<%= question.attributes["id"] %>').value;"></input>&nbsp;&nbsp;<input type="button" value="取消" onclick="javascript:document.getElementById('change_position_div_<%= question.attributes["id"] %>').style.display='none';"></input>&nbsp;&nbsp;&nbsp;&nbsp;</div>
                <div class="chose_add">
                  <a href="javascript:void(0);"
                   onclick="javascript:document.getElementById('change_position_div_<%= question.attributes["id"] %>').style.display='block';">换序(<%= @colligation_index %>)</a>&nbsp;
                  <a href="/problems/delete_colligation_question?question_id=<%= question.attributes["id"].to_i %>&xml_id=<%= @xml.attributes["id"] %>&question_xpath=<%= question.xpath %>" onclick ="return confirm('确认要删除该小题么 ?')" >删除</a>&nbsp;
                  <a href="javascript:void(0);"
                     onclick="javascript:edit_question(<%= question.attributes["id"].to_i %>,'<%= @xml.attributes["id"] %>', '<%= question.xpath %>')">编辑</a>
                </div>
                <div class="clear"></div>
              </div>
            </div>
          <% else %>
            <%= render :partial => "/common/edit_other_question", :object => question %>
          <% end %>
        <% end %>
        <input type="hidden" name="all_question_ids_<%= edit_problem.attributes["id"] %>"
               id="all_question_ids_<%= edit_problem.attributes["id"] %>" value="<%= question_ids.to_s %>" />
        <input type="hidden" name="edit_coll_question_<%= edit_problem.attributes["id"] %>"
               id="edit_coll_question_<%= edit_problem.attributes["id"] %>" value=""/>
        <br/><p>题目的位置：<input type="text" name="insert_position" value=""/> 注：不填则保持原位</p>
        <%= f.submit "提交" , :class=>"submit_btn" %>
      <% end %>
    </div>
  </div>
</div>

app/views/papers/_question_info.erb
<div class="products_list_style_box" id="question_info_<%= question_info.attributes["id"].to_i %>" style="display:none">
  <div class="arrow" style="top:35px;"></div>
  <div class="big_pic_box" style="top:0px;">
    <div class="in">
      <div class="title">
        <% if question_info.elements["title"].nil? or question_info.elements["title"].text.nil? or
            question_info.elements["title"].text == "" %>
        暂无标题
        <% else %>
        <%= question_info.elements["title"].text.to_s.html_safe %>
        <% end %>
      </div>
      <% question_info.elements["questions"].each_element do |question| %>
        <%= render :partial => "/common/show_single_question", :object => question %>
      <% end %>
    </div>
  </div>
</div>